sonar.projectKey=projet-flask-minepat
sonar.projectName=Projet Flask MINEPAT
sonar.projectVersion=1.0
sonar.language=py
sonar.sources=.
sonar.exclusions=**/static/**,**/templates/**,**/__pycache__/**,**/*.pyc,**/*.db,**/exports/**
sonar.tests=tests
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://20.76.124.159:9000