sonar.projectKey=projet-flask-minepat
sonar.projectName=Projet Flask MINEPAT
sonar.projectVersion=1.0
sonar.language=py
sonar.sources=projet-flask V6
sonar.exclusions=**/static/**,**/templates/**,**/__pycache__/**,**/*.pyc,**/*.db,**/exports/**
sonar.tests=projet-flask V6/tests
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=projet-flask V6/coverage.xml
sonar.python.xunit.reportPath=projet-flask V6/test-results.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://20.76.124.159:9000
sonar.branch.name=